
services:
  web:
    depends_on:
      - api
    build: ./frontend

    ports:
      - "5173:5173"

    environment:
      VITE_API_URL: http://localhost:8000

    develop:
      watch:
        - path: ./frontend/package.json
          action: rebuild
        - path: ./frontend/package-lock.json
          action: rebuild

        - path: ./frontend
          target: /app
          action: sync


  api:
    depends_on:
      db:
        condition: service_healthy


    build: ./backend
    ports:
      - "8000:8000"

    env_file:
      - ./backend/.env

    environment:
      DATABASE_URL: postgresql://devtrack_user:devtrack_password@db:5432/devtrack

    develop:
      watch:
        - path: ./backend
          target: /app
          action: sync

  db:
    image: postgres:15-alpine
    container_name: devtrack_db
    restart: always
    environment:
      POSTGRES_USER: devtrack_user
      POSTGRES_PASSWORD: devtrack_password
      POSTGRES_DB: devtrack
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U devtrack_user -d devtrack" ]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:


